// This file is automatically generated from your CSS. Any edits will be overwritten.
export const upcoming: string;
export const time: string;
export const subject: string;
export const room: string;
