// This file is automatically generated from your CSS. Any edits will be overwritten.
export const grades: string;
export const gradeBox: string;
export const details: string;
export const grade: string;
