// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const buttonDownload: string;
export const buttonLogin: string;
export const mobile: string;
