// This file is automatically generated from your CSS. Any edits will be overwritten.
export const logo: string;
export const container: string;
export const sideimage: string;
export const afterheaderpadding: string;
export const infobox: string;
export const button: string;
export const colored: string;
export const disabled: string;
export const links: string;
export const menu: string;
