// This file is automatically generated from your CSS. Any edits will be overwritten.
export const warning: string;
export const container: string;
export const buttons: string;
export const button: string;
